pipeline:
  identifier: Build_handplaned_harness_1728480453625
  name: Build harness
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1728480430907
        repoName: handplaned/harness
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.8-jdk-11
                    shell: Sh
                    command: |
                      mvn clean package dependency:copy-dependencies
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: docker_harness
                    repo: handplaned/harness
                    tags:
                      - handplaned
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          buildIntelligence:
            enabled: false
        type: CI
        description: ""
